# Generated by Django 4.2.16 on 2024-10-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_deck_material', models.CharField(max_length=50)),
                ('lower_deck_material', models.CharField(max_length=50)),
                ('fingerboard_material', models.CharField(max_length=50)),
                ('frets', models.IntegerField()),
                ('pickup', models.CharField(max_length=50)),
                ('strings', models.IntegerField()),
                ('image', models.ImageField(upload_to='guitars/')),
            ],
        ),
    ]
